[안혜수] ClassDetail page left side layout
wecode-bootcamp-korea/14-2nd-CLNASS101-frontend pull request #11
Opened 2020-12-04 17:30 UTC by hyesoo-ahn

## 수정 사항 간략한 한줄 요약
- 좌측 강의페이지 레이아웃 완료
		 
## 수정 사항들 자세한 내용
- 좌측 강의페이지 레이아웃 완료

## 기타 질문 및 특이 사항
- 목업데이터 어떤 방식으로 만들어야 할 지 모르겠어요 ㅠㅠ

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-07 01:47 UTC, dipsiiiiiiiiii commented
혜수님! 목업 데이터 먼저 만들어 보신 거 공유해주세요!

2020-12-07 12:38 UTC, claire-euni reviewed
리뷰반영해서 리팩토링 진행해주세요~

2020-12-07 12:38 UTC, claire-euni commented on src/Pages/ClassDetail/ClassDetail.js
> +    .lectureTitle {
엔터 간격 한 줄 주세요~

2020-12-07 12:38 UTC, claire-euni commented on src/Pages/ClassDetail/ClassDetail.js
> +      align-items: center;
변수명으로 빼서 extend 사용해보세요!

2020-12-07 12:38 UTC, claire-euni commented on src/Pages/ClassDetail/ClassDetail.js
> +      box-sizing: border-box;
이 속성은 이미 common.scss나 globalStyle에서 주는 부분같네요 !

2020-12-07 12:38 UTC, claire-euni commented on src/Pages/ClassDetail/CommentInput.js
> +import { useState, useEffect } from 'react';
하나로 합칠 수 있겠죠?

2020-12-07 12:38 UTC, claire-euni commented on src/Pages/ClassDetail/CommentInput.js
> +    addContent.push({ comment, idx: Date.now() });
state인 addContent를 수정하고 싶으신거라면 단순히 push로 업데이트 시키는게 아니라 setState함수를 사용해주셔야합니다.

2020-12-07 12:38 UTC, claire-euni commented on src/Pages/ClassDetail/CommentInput.js
> +const CommentContainer = styled.form`
스타일컴포넌트로 조금더 세분화하면 좋을 것 같습니다!

2020-12-08 06:41 UTC, hyesoo-ahn commented on src/Pages/ClassDetail/ClassDetail.js
> +      box-sizing: border-box;
넹!

2020-12-08 06:42 UTC, hyesoo-ahn commented on src/Pages/ClassDetail/CommentInput.js
> +import { useState, useEffect } from 'react';
굿..

2020-12-08 06:51 UTC, hyesoo-ahn commented on src/Pages/ClassDetail/CommentInput.js
> +    addContent.push({ comment, idx: Date.now() });
수정했습니다!

2020-12-08 10:55 UTC, Jun4928 commented
@hyesoo-ahn  
혜수님 현재 PR 리베이스 다시 해주세요!
그리고, 충돌해결하면서 `<<<<< HEAD` `=======` 이런 충돌 내역이 남아있습니다.

2020-12-08 10:55 UTC, Jun4928 requested changes

2020-12-08 10:55 UTC, Jun4928 commented on public/data/HS/data.json
> +<<<<<<< HEAD
🔥

2020-12-08 10:55 UTC, Jun4928 commented on public/data/HS/data.json
> +=======
🔥

2020-12-09 05:05 UTC, hyesoo-ahn commented on public/data/HS/data.json
> +<<<<<<< HEAD
해결완료..!

2020-12-09 05:05 UTC, hyesoo-ahn commented on public/data/HS/data.json
> +=======
해결 완..!

2020-12-09 05:54 UTC, claire-euni reviewed
혜수님 스타일 컴포넌트 부분만 리팩토링 좀 더 해주시면 간결해질 것 같네요!

2020-12-09 05:54 UTC, claire-euni commented on src/Pages/ClassDetail/CommentInput.js
> +    addContent.push({ comment, idx: Date.now() });
idx에 Date()를 사용하시는 이유가 있을까요?

2020-12-09 05:54 UTC, claire-euni commented on src/Pages/ClassDetail/ClassDetail.js
> +        align-items: center;
혜수님 아래와 같은 방식으로 extend 할 수 있답니다. 한번 사용해보세요 ~

```suggestion
const displayCenter = styled.css`
        display: flex;
        justify-content: center;
        align-items: center;
`

const Container = styled.div`
 ${displayCenter}
`
  
```

2020-12-10 07:49 UTC, merged