[안혜수] ClassLists 페이지 구현중
wecode-bootcamp-korea/14-2nd-CLNASS101-frontend pull request #9
Opened 2020-12-02 10:20 UTC by hyesoo-ahn

## 수정 사항 간략한 한줄 요약
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-07 12:31 UTC, claire-euni reviewed
혜수님 리뷰반영해서 리팩토링 해주세요 화이팅🤗

2020-12-07 12:31 UTC, claire-euni commented on .gitignore
> +.eslintcache
👍👍👍

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/ClassLists.js
> +import styled from 'styled-components';
import 순서 다시 확인해주세요~

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/ClassLists.js
>  class ClassLists extends Component {
import와 컴포넌트 선언 부분은 엔터간격 한줄 주시는게 가독성에 좋습니다 :)

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/ClassLists.js
> +    const dd = [...this.state.curriculum];
이미 curriculum이 [] 배열 상태인데 spread 연산자가 필요한가요? 
dd로 변수설정할 필요없이 바로 state.curriculum으로 가져와도 되지 않을까요~?

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/ClassLists.js
> +    const newdata = { ...this.state.classdata };
이 부분도 마찬가지로 classdata를 새로운 변수에 담는 이유가 있을까요?

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/ClassLists.js
> +                      <div className='c'>{classdata.title}</div>
클래스명을 고민해보세요 🙌

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/ClassLists.js
> +
불필요한 엔터간격입니다

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/ClassLists.js
> +                  <div className='box1'>
클래스명은 무슨 기능을 하는지 어떤 컨텐츠를 담고 있는지 명확하게 나타내는 네이밍이 좋습니다. 고민해보세요~

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/ClassLists.js
> +  .nav {
속성이 있는 경우는 엔터간격 한 줄 주는게 좋습니다~

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/ClassLists.js
> +      align-items: center;
자주 사용되는 속성이라면 변수로 설정하고 extend로 재사용하시는 방법을 사용해보세요~

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/ClassLists.js
> +const NavContainer = styled.div`
현재 스타일 컴포넌트를 크게 6개로만 나누셨는데 스타일 컴포넌트도 기존 컴포넌트와 마찬가지로 재사용이 가능한 속성을 가진 부분들이라면 나눠주는게 좋습니다.

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/RightSideList.js
> +import { withRouter } from 'react-router-dom';
import 순서는 React > Packaged & Library > Component > Style 순서입니다. 고려해서 수정해주세요

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/RightSideList.js
> +  };
무슨 기능을 하는 함수인지 알 수 없으므로 명확한 네이밍으로 수정해주세요

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/RightSideList.js
> +      <>
이미 부모태그가 감싸고 있는 형태라고 빈태그로 굳이 감싸주지 않아도 될 것 같습니다

2020-12-07 12:31 UTC, claire-euni commented on src/Pages/ClassLists/RightSideList.js
> +//   }
주석처리하신 부분은 필요없는 부분인가요? 그러면 삭제해주세요~

2020-12-08 03:28 UTC, hyesoo-ahn commented on src/Pages/ClassLists/ClassLists.js
>  class ClassLists extends Component {
넹 ~

2020-12-08 03:28 UTC, hyesoo-ahn commented on src/Pages/ClassLists/ClassLists.js
> +    const dd = [...this.state.curriculum];
오호...그렇군요...

2020-12-08 03:32 UTC, hyesoo-ahn commented on src/Pages/ClassLists/RightSideList.js
> +import { withRouter } from 'react-router-dom';
헉 감사합니다 ㅜㅜ

2020-12-08 03:59 UTC, hyesoo-ahn commented on src/Pages/ClassLists/RightSideList.js
> +  };
수정했습니다~

2020-12-08 04:03 UTC, hyesoo-ahn commented on src/Pages/ClassLists/RightSideList.js
> +//   }
넵 !

2020-12-08 05:37 UTC, claire-euni commented
혜수님 아까 dm으로 말씀드린대로 일단 오늘은 리뷰반영해서 기존 PR 리팩토링 먼저하시고 
지금 rebase되어 있지 않은 상태라서 git rebase로 커밋내역 하나로 줄여서 push해주세요.🤗

2020-12-08 08:03 UTC, Jun4928 requested changes
혜수님, map 함수와 객체 spread 연산자에 대한 리뷰 남겨드렸습니다.
궁금하신 사항 있으면 언제든 질문 주세요! 🙌

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/ClassLists.js
> +      curriculum: [],
### 변수명 컨벤션
- 변수명의 이름에 `data`, `list`, `info` 등의 의미없는 단어를 삭제 해 주세요. 
개발자는 변수에 데이터가 담긴다는 것을 이미 알고 있습니다.
- 배열은 `복수`로 변수명을 짓는것이 컨벤션 입니다. 

ex)
```js
this.state = {
  class: {},
  curriculums: [],
}
```

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/ClassLists.js
> +  handleButtonClick = (el) => {
## 함수명과 인자의 이름
함수의 이름과 인자의 이름을 통해서 함수의 의도를 드러낼 수 있어야 합니다.

1. handleButtonClick: 어떤 버튼을 클릭한 건가요?
2. el: el 이 무엇인가요?

이렇게 의문점을 가지게 하면 안됩니다.

코드의 내용을 보고 판단하면 커리큘럼에 대해 map 함수로 렌더링하고 있는 <RightSideList> 컴포넌트 안 버튼에 이벤트를 바인딩 시키고 있고, index를 인자로 받고있으므로 저라면 다음과 같은 이름을 사용할 것 같습니다.
```js
handleClassProgress = (curriculumIndex) => {

}
```

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/ClassLists.js
> +    const curriculum = [...this.state.curriculum];
state 에 담긴 curriculm (배열)을 새로 복사 할 필요가 없습니다.
구조분해할당을 하면, 그 시점의 상태에 저장된 curriculum 을 그대로 새로운 변수에 할당할 수 있습니다.
```js
const { curriculums } = this.state
```

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/ClassLists.js
> +    console.log(count);
콘솔 삭제 해 주세요

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/ClassLists.js
> +    }
위에서 구조분해할당 한 curriculum 에 대해서 map 함수를 사용하면 새로운 배열을 만들어 낼 수 있습니다.
```js
// map 함수는 callback 함수를 받고
// callback 함수의 첫번째 인자는 배열의 요소가 됩니다. 이 경우 하나의 curriculum 객체가 되겠죠?
let count = 0
const newCurriculumns = curriculums.map((curriculum) => {
  if (curriculum.id === curriculumIdex) { // 커리큘럼 인덱스가 같을 때
    count += 1

    return { // 새로운 객체를 리턴 합니다.
      ...curriculum, // 원본 객체를 spread 로 복사하고, 
      isPlayed: true // 바꾸고자 하는 속성값을 가장 하단에 적어주면 덮어쓰기가 됩니다.
    }
  }
  
  if (curriculum.isPlayed) count += 1 
  return curriculum // 커리큘럼 인덱스가 같지 않을 때에는 원본 객체를 리턴해서 새로운 배열에 담습니다.
})
```

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/ClassLists.js
> +        : parseInt(100 / curriculum.length) * count;
새로운 객체를 만들 때에도 위에 리뷰 남겨드린 것 처럼 spread 연산자를 사용하고 바꾸고자 하는 속성 값을 가장 하단에 적어주면 덮어쓰기가 되는 성질을 이용해서 리팩토링 할 수 있습니다.
```js
const newClass = {
  ...this.state.class,
  progress: count === curriculums.length ? 100 : parseInt(100 / curriculum.length) * count
}
```

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/ClassLists.js
> +    });
여기도 다음과 같이 바뀌게 되겠죠
```js
this.setState({
  curriculums: newCurriculums,
  class: newClass
})
```

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/ClassLists.js
> +    console.log(this.props);
🔥

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/RightSideList.js
> +    console.log(this.props);
🔥

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/RightSideList.js
> +  };
props로 내려온 `getEvent` 함수를 다시 한 번 메소드로 만들 이유가 없습니다.
이벤트가 발생하는 곳에서 바로 binding 시켜 주세요!

2020-12-08 08:03 UTC, Jun4928 commented on src/Pages/ClassLists/RightSideList.js
> +              }}>
```js
onClick{() => this.props.getEvent(curriculum.id)}
```

2020-12-08 08:09 UTC, hyesoo-ahn commented on src/Pages/ClassLists/ClassLists.js
> +      curriculum: [],
최고..

2020-12-08 09:27 UTC, hyesoo-ahn commented on src/Pages/ClassLists/ClassLists.js
> +    const curriculum = [...this.state.curriculum];
넵!

2020-12-08 09:29 UTC, hyesoo-ahn commented on src/Pages/ClassLists/ClassLists.js
> +    }
오...!

2020-12-08 09:53 UTC, hyesoo-ahn commented on src/Pages/ClassLists/ClassLists.js
> +      curriculum: [],
근데 classdata를 class로 고치는 과정에서 제가 뭘 놓친건지 모르겠는데 계속 에러가 떠서 ㅜㅜ curriculum은 고쳤는데 classdata는 못 고쳤어요 ㅠㅠㅠㅠㅠㅠㅠㅠㅠ

2020-12-08 10:48 UTC, Jun4928 commented
@hyesoo-ahn 혜수님 커밋내역이 4개나 있습니다. 
리베이스 해 주세요, 그리고 리뷰 반영이 아직 덜 된 것 같습니다!

2020-12-08 10:57 UTC, Jun4928 commented on src/Pages/ClassLists/ClassLists.js
> +      curriculum: [],
- 혜수님, `cmd+f` 로 classData 전체를 class로 바꾸면 되지 않을까요?
- 또한, 리액트에서 에러를 낼 때, 어떤 파일에 몇번째 줄에 에러가 나고 있는지 알려줍니다.

두 가지 이용해서 수정해주세요!

2020-12-08 16:56 UTC, hyesoo-ahn commented on src/Pages/ClassLists/RightSideList.js
> +  };
수정했습니당

2020-12-09 13:09 UTC, hyesoo-ahn commented on src/Pages/ClassLists/ClassLists.js
> +      curriculum: [],
수정했습니다!

2020-12-10 05:14 UTC, merged